//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theCoffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuNhap
    {
        public int MaCTPN { get; set; }
        public Nullable<int> MaPN { get; set; }
        public string TenHang { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<long> SoLuong { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<double> TongGia { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
